console:
  build: .
  command: python rw_visual.py
#  ports:
#   - "5000:5000"
  environment:
    - DISPLAY=unix$DISPLAY
  volumes:
   - .:/src
   - /tmp/.X11-unix:/tmp/.X11-unix
#  stdin_open: true
#  tty: true